In [1]:
import pandas as pd

In [33]:
df = pd.read_csv('load_file_openAQ.csv')

In [34]:
df.head()

,id,name,locality,timezone,is_mobile,is_monitor,instruments,sensors,bounds,distance,...,owner.id,owner.name,provider.id,provider.name,coordinates.latitude,coordinates.longitude,datetime_first.utc,datetime_first.local,datetime_last.utc,datetime_last.local
0,5994,Nairobi CBD,NaN,Africa/Nairobi,False,True,"[{'id': 2, 'name': 'Government Monitor'}]","[{'id': 16244, 'name': 'pm10 µg/m³', 'paramete...","(36.81883, -1.28156, 36.81883, -1.28156)",554.630213,...,4,Unknown Governmental Organization,120,AirNow Kenya,-1.281560,36.818830,2018-04-23T00:00:00Z,2018-04-23T03:00:00+03:00,2018-09-13T21:00:00Z,2018-09-14T00:00:00+03:00
1,6317,Alliance Girls High,NaN,Africa/Nairobi,False,True,"[{'id': 2, 'name': 'Government Monitor'}]","[{'id': 17575, 'name': 'pm10 µg/m³', 'paramete...","(36.66314, -1.26614, 36.66314, -1.26614)",17289.961365,...,4,Unknown Governmental Organization,120,AirNow Kenya,-1.266140,36.663140,2018-04-21T00:00:00Z,2018-04-21T03:00:00+03:00,2018-11-20T23:00:00Z,2018-11-21T02:00:00+03:00
2,352507,Nairobi RR,NaN,Africa/Nairobi,False,True,"[{'id': 2, 'name': 'Government Monitor'}]","[{'id': 2002532, 'name': 'pm25 µg/m³', 'parame...","(36.81732, -1.23437, 36.81732, -1.23437)",5742.165573,...,4,Unknown Governmental Organization,119,AirNow,-1.234370,36.817320,2022-06-16T17:00:00Z,2022-06-16T20:00:00+03:00,2025-02-12T15:00:00Z,2025-02-12T18:00:00+03:00
3,2156118,Nairobi,NaN,Africa/Nairobi,False,False,"[{'id': 4, 'name': 'Clarity Sensor'}]","[{'id': 7765850, 'name': 'no2 ppb', 'parameter...","(36.91271, -1.33159, 36.91271, -1.33159)",11750.016542,...,9,Clarity,166,Clarity,-1.331590,36.912710,2024-01-28T15:00:32Z,2024-01-28T18:00:32+03:00,2025-10-16T05:47:28Z,2025-10-16T08:47:28+03:00
4,2388059,"Nyayo Embakasi, Nairobi",NaN,Africa/Nairobi,False,False,"[{'id': 7, 'name': 'Unknown AirGradient Sensor...","[{'id': 7981687, 'name': 'pm1 µg/m³', 'paramet...","(36.907681, -1.304011, 36.907681, -1.304011)",10258.411936,...,11509,Unknown Person,66,AirGradient,-1.304011,36.907681,2024-02-06T05:00:00Z,2024-02-06T08:00:00+03:00,2024-05-09T18:00:00Z,2024-05-09T21:00:00+03:00

In [35]:
df[['id', 'name', 'sensors']]

,id,name,sensors
0,5994,Nairobi CBD,"[{'id': 16244, 'name': 'pm10 µg/m³', 'paramete..."
1,6317,Alliance Girls High,"[{'id': 17575, 'name': 'pm10 µg/m³', 'paramete..."
2,352507,Nairobi RR,"[{'id': 2002532, 'name': 'pm25 µg/m³', 'parame..."
3,2156118,Nairobi,"[{'id': 7765850, 'name': 'no2 ppb', 'parameter..."
4,2388059,"Nyayo Embakasi, Nairobi","[{'id': 7981687, 'name': 'pm1 µg/m³', 'paramet..."
5,3394396,Nairobi CMR,"[{'id': 12151945, 'name': 'pm25 µg/m³', 'param..."
6,3394397,Nairobi CMR,"[{'id': 12161516, 'name': 'pm25 µg/m³', 'param..."
7,3399524,Nairobi RR,"[{'id': 12167724, 'name': 'pm25 µg/m³', 'param..."
8,5119477,Kitisuru,"[{'id': 13633454, 'name': 'pm1 µg/m³', 'parame..."
9,5199863,Kihumo Village || Antenna Array,"[{'id': 13691748, 'name': 'pm1 µg/m³', 'parame..."
10,5672958,KENBIFS01,"[{'id': 14341710, 'name': 'bc_375 ng/m³', 'par..."
11,5672959,KENBIMLK01,"[{'id': 14341714, 'name': 'bc_375 ng/m³', 'par..."
12,6216058,Mukuru- Pipeline,"[{'id': 15269707, 'name': 'pm1 µg/m³', 'parame..."
13,6236592,Marurui,"[{'id': 15420153, 'name': 'pm1 µg/m³', 'parame..."
14,6237507,Providence Academy,"[{'id': 15427114, 'name': 'pm1 µg/m³', 'parame..."
15,6326576,"Nairobi, University of Nairobi, Parklands Camp...","[{'id': 16091678, 'name': 'pm25 µg/m³', 'param..."